"use client";
import { motion } from "framer-motion";
import { ReactLenis } from "lenis/react";
import Navbar from "@/components/landing/Navbar";
import CTAFooter from "@/components/landing/CTAFooter";
import { FileText, AlertTriangle, CreditCard, Users, Gavel, Code2 } from "lucide-react";

const sections = [
  {
    icon: FileText,
    title: "Acceptance of Terms",
    accent: "#00F0FF",
    content: [
      {
        subtitle: "Agreement",
        body: "By accessing or using Archi.dev (\"Service\"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.",
      },
      {
        subtitle: "Eligibility",
        body: "You must be at least 16 years old and capable of forming a binding contract to use Archi.dev. By using the Service, you represent that you meet these requirements.",
      },
      {
        subtitle: "Updates to terms",
        body: "We reserve the right to modify these terms at any time. We will provide at least 14 days notice for material changes. Continued use of the Service after changes constitutes acceptance.",
      },
    ],
  },
  {
    icon: Code2,
    title: "Service Description",
    accent: "#8A2BE2",
    content: [
      {
        subtitle: "What we provide",
        body: "Archi.dev is a visual backend architecture design and code generation platform. The Service allows you to design, generate, and deploy backend systems using an AI-assisted visual canvas.",
      },
      {
        subtitle: "Generated code",
        body: "All code generated by Archi.dev is owned by you. We grant you a perpetual, irrevocable, worldwide license to use the generated output for any lawful purpose.",
      },
      {
        subtitle: "Service availability",
        body: "We aim for 99.9% uptime but do not guarantee uninterrupted service. Scheduled maintenance windows are announced at least 24 hours in advance via status.archi.dev.",
      },
    ],
  },
  {
    icon: CreditCard,
    title: "Credits & Billing",
    accent: "#28C840",
    content: [
      {
        subtitle: "Credit system",
        body: "The Service operates on a credit-based model. Each AI generation operation consumes one credit. Free plan users receive 500 credits monthly. Paid plans receive larger monthly allocations.",
      },
      {
        subtitle: "No rollover",
        body: "Monthly free credits expire at the end of each calendar month and do not roll over. Purchased top-up credits do not expire until used.",
      },
      {
        subtitle: "Refunds",
        body: "Subscription fees are non-refundable except where required by law. If you cancel a paid plan, you retain access until the end of the billing period.",
      },
    ],
  },
  {
    icon: AlertTriangle,
    title: "Prohibited Uses",
    accent: "#FF6B82",
    content: [
      {
        subtitle: "Prohibited activities",
        body: "You may not use Archi.dev to generate code intended for malicious purposes, to circumvent security systems, to violate any laws, or to infringe on the intellectual property of others.",
      },
      {
        subtitle: "Abuse of the platform",
        body: "You may not attempt to reverse-engineer the AI models, scrape the platform at scale, create multiple free accounts to bypass credit limits, or resell access to the Service.",
      },
      {
        subtitle: "Content restrictions",
        body: "Architecture diagrams and prompts must not contain illegal content. We reserve the right to remove content and suspend accounts that violate this policy without notice.",
      },
    ],
  },
  {
    icon: Users,
    title: "Team Plans",
    accent: "#F5A623",
    content: [
      {
        subtitle: "Workspace ownership",
        body: "Team workspace owners are responsible for all activity within their workspace, including the actions of invited members. Owners must ensure all members comply with these terms.",
      },
      {
        subtitle: "Seat limits",
        body: "Team plan seats are per-user. Sharing account credentials to circumvent seat limits is prohibited and may result in account termination.",
      },
      {
        subtitle: "Data on team removal",
        body: "When a member is removed from a team workspace, they lose access to shared projects. Projects remain with the workspace owner.",
      },
    ],
  },
  {
    icon: Gavel,
    title: "Liability & Governing Law",
    accent: "#00F0FF",
    content: [
      {
        subtitle: "Limitation of liability",
        body: "Archi.dev is provided \"as is\" without warranties of any kind. To the maximum extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from use of the Service.",
      },
      {
        subtitle: "Indemnification",
        body: "You agree to indemnify Archi.dev and its team from any claims arising from your use of the Service, your generated output, or your violation of these terms.",
      },
      {
        subtitle: "Governing law",
        body: "These terms are governed by the laws of the jurisdiction in which Archi.dev is incorporated. Disputes will be resolved through binding arbitration except where prohibited by law.",
      },
    ],
  },
];

export default function TermsPage() {
  return (
    <ReactLenis root>
      <main className="bg-black min-h-screen overflow-x-hidden">
        <Navbar />

        {/* Hero */}
        <section className="relative pt-40 pb-16 px-6 overflow-hidden">
          <div className="section-top-line" />
          <div
            className="absolute inset-0 pointer-events-none"
            style={{ background: "radial-gradient(ellipse 60% 40% at 50% 0%, rgba(0,240,255,0.05) 0%, transparent 65%)" }}
          />
          <div className="bg-grid absolute inset-0 pointer-events-none opacity-30" />

          <div className="max-w-3xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
              className="mb-6"
            >
              <span className="inline-flex items-center gap-2 glass-panel px-5 py-2 rounded-full text-[#00F0FF] text-xs font-semibold uppercase tracking-[0.2em] border border-white/[0.06]">
                <span className="w-1.5 h-1.5 rounded-full bg-[#00F0FF] animate-glow-cyan" />
                Legal
              </span>
            </motion.div>

            <motion.h1
              initial={{ y: 24, opacity: 0, filter: "blur(10px)" }}
              animate={{ y: 0, opacity: 1, filter: "blur(0px)" }}
              transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1], delay: 0.1 }}
              className="text-gradient font-medium tracking-tighter leading-[0.9] mb-5"
              style={{ fontSize: "clamp(2.8rem, 6vw, 5rem)" }}
            >
              Terms of Service
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1], delay: 0.2 }}
              className="text-white/40 text-base max-w-xl mx-auto leading-relaxed"
            >
              Last updated <span className="text-white/65">March 24, 2026</span>. Please read these terms carefully before using Archi.dev.
            </motion.p>
          </div>
        </section>

        {/* Content */}
        <section className="px-6 pb-28 md:px-16 xl:px-24">
          <div className="max-w-4xl mx-auto space-y-6">
            {sections.map((section, i) => {
              const Icon = section.icon;
              return (
                <motion.div
                  key={section.title}
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-40px" }}
                  transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1], delay: i * 0.05 }}
                  className="bento-card rounded-2xl p-7 relative overflow-hidden group"
                >
                  <div
                    className="pointer-events-none absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-2xl"
                    style={{ background: `radial-gradient(400px circle at 30% 50%, ${section.accent}0a, transparent 70%)` }}
                  />

                  <div className="flex items-center gap-3 mb-6">
                    <div
                      className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0"
                      style={{ backgroundColor: `${section.accent}18` }}
                    >
                      <Icon size={16} style={{ color: section.accent }} />
                    </div>
                    <h2 className="text-white font-semibold text-lg tracking-tight">{section.title}</h2>
                  </div>

                  <div className="space-y-5">
                    {section.content.map((item) => (
                      <div key={item.subtitle} className="pl-4 border-l-2" style={{ borderColor: `${section.accent}30` }}>
                        <div className="text-white/75 text-sm font-semibold mb-1.5">{item.subtitle}</div>
                        <p className="text-white/40 text-sm leading-relaxed">{item.body}</p>
                      </div>
                    ))}
                  </div>
                </motion.div>
              );
            })}

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
              className="bento-card rounded-2xl p-6 text-center"
            >
              <p className="text-white/30 text-sm leading-relaxed">
                Questions about these terms? Contact <span className="text-[#00F0FF]/70">legal@archi.dev</span>
                <br />These terms were last updated on March 24, 2026 and supersede all previous versions.
              </p>
            </motion.div>
          </div>
        </section>

        <CTAFooter />
      </main>
    </ReactLenis>
  );
}
